### ISSUE TITLE
demo images not appearing

### ISSUE THREAD

**Issue by nxmohamad** [sherubthakur/react-horizontal-timeline#23]
I've just cloned the repo to test it out. I see that there are image props, but no image is showing.

**Comment by nxmohamad** [comment]
ok so this is simply because there's no image tag in the this.data part. perhaps the code should be updated.

**Comment by sherubthakur** [comment]
Unsure what you are saying here. Can you add more details.

**Comment by nxmohamad** [comment]
in demo-swipeable-view's index.js is the following code:

<div className='container' key={index}>
            <h1>{ `The Elder Scrolls ${index + 1}:`}</h1>
            <h2>{ game.subtitle }</h2>
            <hr />
            <p>{ game.content}</p>
            <hr />
</div>

it doesn't make use of the image url prop in the data file.

**Comment by nxmohamad** [comment]
image tag should be added

`<div className='container' key={index}>
            <h1>{ `The Elder Scrolls ${index + 1}:`}</h1>
            <image src={game.avatarURL} />
            <h2>{ game.subtitle }</h2>
            <hr />
            <p>{ game.content}</p>
            <hr />
</div>`

**Comment by sherubthakur** [comment]
ah ok so this is what you were saying, will add them sometime.
