### ISSUE TITLE
Demo URLs in repo header and on README are deadlinks

### ISSUE THREAD

**Issue by aliceyoung9** [sherubthakur/react-horizontal-timeline#25]
They're also different? 
http://sherubthakur.github.io/react-horizontal-timeline and 
http://jckdrpr.github.io/react-horizontal-timeline

Thanks!

**Comment by sherubthakur** [comment]
Ah! I changed my username and forgot to update the readme. Should be fixed now though.

Thanks

**Comment by aliceyoung9** [comment]
thanks!
