### ISSUE TITLE
Require react-icon-base problem in v1.3.0

### ISSUE THREAD

**Issue by misogl** [sherubthakur/react-horizontal-timeline#27]
In version 1.3.0 the build output file `dist/react-horizontal-timeline.js` contains `require("react-icon-base")`. This reference cannot be resolved as it is not in package dependencies.

I'm using yarn v1.1.0 which does not install indirect dependency `react-icon-base` into the root `node_modules` directory but under `react-icons/node_modules` and webpack is unable to resolve it in that case.

Please fix the build configuration.

**Comment by misogl** [comment]
Thanks for the fast response. Could you please publish a new version with the fixes?

**Comment by sherubthakur** [comment]
Done
