### ISSUE TITLE
Able to remove button-back and button-forward

### ISSUE THREAD

**Issue by surmistry** [sherubthakur/react-horizontal-timeline#35]
Hi there, love the library and great UX. I just wanted to remove the ability to scroll through the dates and dislay them all in a simple line but I can't figure out how to remove the forward and back buttons if that's possible? TIA

**Comment by sherubthakur** [comment]
@surmistry Really happy that you like the lib, and as for the query I am afraid that what you desire here is not the intended behaviour.
@Nickman87  do you think it would be worthwhile to implement this feature?

**Comment by Nickman87** [comment]
@surmistry I don't understand what you are trying to achieve? You don't want the user to be able to scroll trough the list, does this mean you want the option to control the scrolling from outside of the component?

If you just want to hide the buttons, you could put a `display: invisible` style on the `buttons` class?

**Comment by surmistry** [comment]
Thanks @Nickman87 that's what I was looking for, got it working using
`display: none;`
