### ISSUE TITLE
Doesn't render when in a container with display:none

### ISSUE THREAD

**Issue by BradMcGovern** [sherubthakur/react-horizontal-timeline#36]
I'm using this as a timeline for projects. I'm creating a new application where there are three pages, and each page has several projects. I need all the pages rendered, but only one to show at a time, so I create all three and hide all but the one that should be shown. In the projects rendered o the page that's not hidden, the timelines appear fine, but when I move to a different page, there's just a '0' in place of the timeline

**Comment by sherubthakur** [comment]
@BradMcGovern Thanks for the report.

_I need all the pages rendered_
Interesting, been out of the whole js/react game for a while but from what I recall people usually don't need to do that.

Can you please create (and share) a minimal project with this issue so we can also see what you mean here and try to find the underlying issue?

**Comment by BradMcGovern** [comment]
I'm new to React, maybe I'm doing it wrong..?  We use it with redux, the idea here is that each element that is created has props that need to be persistent, for example a hidden state. The user can choose elements to hide, and then when they flip to a different page, and then back to this page, the things that were hidden need to still be hidden. I do that by giving each their own isHidden prop in their own state; if the element was re-rendered each time it would destroy that. The other option would be to create a bunch of new variables for each element I'm rendering in the store, but I thought the way I'm doing it seems better.

As for a project, just take one you already have and add "display:none" to a parent container when it's rendered. Then remove that prop in the debugger and you'll see what I mean.

**Comment by sherubthakur** [comment]
Closing.
Re-open requirements: A minimal project with the aforementioned issue.
