### ISSUE TITLE
Cannot run demos on clone

### ISSUE THREAD

**Issue by rburgst** [sherubthakur/react-horizontal-timeline#39]
when I clone this repo and then do 
```
npm install
npm run start
```

then I get the following errors

```

ERROR in ./demos/demo-swipeable-views/index.js
Module not found: Error: Can't resolve 'react' in '/Users/rainer/git/react-horizontal-timeline/demos/demo-swipeable-views'
 @ ./demos/demo-swipeable-views/index.js 5:13-29
 @ multi webpack-dev-server/client?http://localhost:5001 webpack/hot/only-dev-server ./demos/demo-swipeable-views/index.js

ERROR in ./demos/demo-swipeable-views/HorizontalTimelineContent.js
Module not found: Error: Can't resolve 'react' in '/Users/rainer/git/react-horizontal-timeline/demos/demo-swipeable-views'
 @ ./demos/demo-swipeable-views/HorizontalTimelineContent.js 11:13-29
 @ ./demos/demo-swipeable-views/index.js
 @ multi webpack-dev-server/client?http://localhost:5001 webpack/hot/only-dev-server ./demos/demo-swipeable-views/index.js
...
```

**Comment by MadalenaGoncalves** [comment]
Any news on this?

**Comment by MadalenaGoncalves** [comment]
Wait, just found it: you have to install the peer dependencies: 
`yarn add react react-dom -P`
And it works ;)

**Comment by sherubthakur** [comment]
@rburgst @MadalenaGoncalves #34 has it covered. Also added the info to readme a9f6a11889427fc44839a846bce4e23f653e284b.

**Comment by rburgst** [comment]
why dont you simply list these dependencies in `package.json` and save everyone the trouble?

**Comment by sherubthakur** [comment]
@rburgst from https://yarnpkg.com/lang/en/docs/dependency-types/.

## peerDependencies
Peer dependencies are a special type of dependency that would only ever come up if you were publishing your own package.

Having a peer dependency means that your package needs a dependency that is the same exact dependency as the person installing your package. This is useful for packages like react that need to have a single copy of react-dom that is also used by the person installing it.

i.e. every lib should not include the version of react (or any other framework/large lib) they depend on as this will lead to multiple react versions in your project.
