### ISSUE TITLE
Problem with button-back, button-forward.

### ISSUE THREAD

**Issue by TTomasik** [sherubthakur/react-horizontal-timeline#41]
After last updates something went wrong. Im using your timeline since version 1.4.0. Before the update buttons back and forward works properly. Right now cursor not-allowed and pointer shows in the wrong moments. For example when I want to scroll to newer dates (button-forward) - I have cursor not-allowed. When Im already on the last dates - button-forward has cursor pointer. The same with button-back :(

**Comment by sherubthakur** [comment]
Hey @TTomasik thanks for the report. I have patched the issue. v1.5.3 on npm should work as intended.

fun-fact: This issue was in the codebase for 3 months or so but never released the code so it didn't crop up till now.

**Comment by TTomasik** [comment]
Thanks! Now everything looks pretty :)
