### ISSUE TITLE
Cannot read property 'map' of undefined - "HorizontalTimelineContent"

### ISSUE THREAD

**Issue by MRMTC** [sherubthakur/react-horizontal-timeline#43]
Hi @sherubthakur :)

Firstly, thanks for the great package - I'm looking forward to using it in my project :)  I was trying to use one of the demos which made use of the content "feature" - it seems like it was used for the demo page that you had listed.  I tried to "simplify" it, and came up with the code seen below:

```JS
import React, { Component } from 'react'; 

import HorizontalTimelineContent from 'react-horizontal-timeline';

import './TimeLine.css';

const game = [
  {
    date: '01/01/1994',
    avatarURL: 'https://upload.wikimedia.org/wikipedia/en/8/89/Elder_Scrolls_Arena_Cover.jpg',
    photo: './the_elder_scrolls_1_arena_wallpaper_by_thejackmoriarty-d8mlpzc.png',
    title: 'The Elder Scrolls: 1',
    subtitle: 'Arena',
    content: 'Boo1'
  },
  {
    date: '08/31/1996',
    avatarURL: 'https://upload.wikimedia.org/wikipedia/en/a/a4/Daggerfall_Cover_art.gif',
    photo: 'https://images6.alphacoders.com/599/599052.jpg',
    title: 'The Elder Scrolls: 2',
    subtitle: 'Daggerfall',
    content: 'Boo2'
  }];

class TimeLine extends Component {
	constructor(props) {
	    super(props);
	    this.state = { value: 0, previous: 0, data: undefined};
  	}

	componentWillMount() {
		let data;

	    data = game.map((game, index) => {
		      return ({
		        date: game.date,
		        component: (
		          <div className='container' key={index}>
		            <h1>{ `The Elder Scrolls ${index + 1}:`}</h1>
		            <h2>{ game.subtitle }</h2>
		            <hr />
		            <p>{ game.content}</p>
		            <hr />
		          </div>
		        )
		      });//end return
		 });//end Data

	    this.setState({ data });
  	}

  	render () {
		return (
			<div className="TimeLine">

				{console.log(this.state.data)}
				<HorizontalTimelineContent content={this.state.data} />

        	</div>
		)//end return
	}//end render

}//end TimeLine

export default TimeLine;
```

However, when I try run it, I get the following error: 
TypeError: Cannot read property 'map' of undefined
t.value
...node_modules/react-horizontal-timeline/dist/react-horizontal-timeline.js:1_

In order to make sure that I was sending through the correct data to the module, I used the "console.log" command seen in the code above.  As per the screenshot below, it does show in the console that there is data present in the object:
![image](https://user-images.githubusercontent.com/26508189/39409667-91414670-4beb-11e8-81f2-18e8e82ab167.png)

Can you please let me know what I am doing wrong?  Is the data perhaps not in the correct format?  I saw somewhere in one of the closed off issues, that the "index" has to be passed through - I tried including it, but couldn't seem to get past this error.

Please let me know if you need any further information in order to assist.

Thanks.

**Comment by sherubthakur** [comment]
Hey @MRMTC this package does not export the `HorizontalTimelineContent` component. That is just a component that I created for the demos if you want an interface like that [this](https://github.com/sherubthakur/react-horizontal-timeline/blob/master/demos/demo-swipeable-views/HorizontalTimelineContent.js#L9) can help you.

So given how imports work in JS you have just created an alias to `HorizontalTimeline` with the name `HorizontalTimelineContent`.

**Comment by MRMTC** [comment]
Ahhhhh I see, thanks for the clarity on this @sherubthakur; and apologies for the confusion on my end.  That was a really silly mistake on my part, I will take the above into consideration when trying to get it to work using the format from your demo.

In parallel though to getting your reply, I did manage to get it work using the simple example from your read me :)  I'm including the code below in case it helps anyone else who may be looking to do something similar on their end.  Thanks again.

`import React, { Component } from 'react'; 

import HorizontalTimeline from 'react-horizontal-timeline';

import './TimeLine.css';

//load images
	import img1 from './Pictures/1.jpg';
	import img2 from './Pictures/2.jpg';
	import img3 from './Pictures/3.jpg';
	import img4 from './Pictures/4.jpg';


const VALUES = [ "December 2013", "13 December 2014", "9 January 2015", "23 January 2015" ];
const styles = { background: '#ABC1D5', foreground: '#7DA1BF', outline: 'black' }

class TimeLine extends Component {
  constructor(props) {
    super(props);
    this.state = { value: 0, previous: 0 };
  }

  	render () {
		return (
			<div className="TimeLine">

				<div>
	        
					<div style={{ width: '60%', height: '100px', margin: '0 auto' }}>
			        	<HorizontalTimeline
			            	index={this.state.value}
			            	indexClick={(index) => {
			              	this.setState({ value: index, previous: this.state.value });
							}}
							values={ VALUES } 
							styles = {styles}
							isTouchEnabled = {true}
							isKeyBoardEnabled = {true}/>
			        </div>

			        <div className='text-center'>
			          {this.TimelineEvents()}
			        </div>

			     </div>				

        	</div>
		)//end return
	}//end render

  	TimelineEvents(){
  		
  		switch(this.state.value) {
	        case 0:
	            return (
		      		<div className="TimeLineFont">
		      			<p>Event 1 Description ♫</p>
						<img alt={""} src={img1} />
					</div>
				)//end return
	        case 1:
	            return (
		      		<div className="TimeLineFont">
		      			<p>Event 2 Description:O</p>
						<img alt={""} src={img2} />
					</div>
				)//end return
	        case 2:
	            return (
		      		<div className="TimeLineFont">
		      			<p>Event 3 Description :)</p>
						<img alt={""} src={img3} />
					</div>
				)//end return
	        case 3:
	            return (
		      		<div className="TimeLineFont">
		      			<p>Event 4 Description ❤</p>
						<img alt={""} src={img4} />
					</div>
				)//end return								
	        default:
	            return null;  //need to cater for possible error case here
    	}

  	}//end TimelineEvents

}//end TimeLine

export default TimeLine;`
