### ISSUE TITLE
Time line not working having error

### ISSUE THREAD

**Issue by shashical** [sherubthakur/react-horizontal-timeline#49]
Am getting bellow error can any one please help me to fix this.
i have installed npm install, webpack, webpack server also  am getting this error.  
I used npm start

ERROR in multi webpack-dev-server/client?http://localhost:5001 webpack/hot/only-dev-server ./demos/demo-swipeable-views/index.js
Module not found: Error: Can't resolve 'babel-loader' in '/home/shashi/Documents/Torrents/NCD/timeset'
 @ multi webpack-dev-server/client?http://localhost:5001 webpack/hot/only-dev-server ./demos/demo-swipeable-views/index.js demo-swipeable-views[2]
ℹ ｢wdm｣: Failed to compile.

**Comment by sherubthakur** [comment]
Unable to replicate.The timeline is working fine. Steps
1. yarn add react react-dom (why you need to do this is described [here](https://github.com/sherubthakur/react-horizontal-timeline#running-the-development-version)
2. yarn install
3. yarn start
