### ISSUE TITLE
Customize TImeline CSS 

### ISSUE THREAD

**Issue by shashical** [sherubthakur/react-horizontal-timeline#50]
Hi, 
I wanted to modify Timeline css ,where should i change Css code.
When i inspect i got li code and tried to change width but in source am not getting css classes 
Example : 
li id="timeline-dot-2018-01-23" class="present dot-label" data-radium="true" style="position: absolute; bottom: 0px; text-align: center; padding-bottom: 15px; left: 57.5px; cursor: pointer; 

> _width: 85px;_

"Jan 23 2018< data-radium="true" style="position: absolute; bottom: -5px; height: 12px; width: 12px; border-radius: 50%; transition: background-color 0.3s ease 0s, border-color 0.3s ease 0s; left: 36.5px; background-color: rgb(26, 121, 173); border: 2px solid rgb(26, 121, 173);"></>li

**Comment by sherubthakur** [comment]
All tweaks go in via props. You cannot directly modify css. Here is an example
git@github.com:sherubthakur/sherubthakur.github.io.git
