### ISSUE TITLE
Format dates (Feature request)

### ISSUE THREAD

**Issue by ticklepoke** [sherubthakur/react-horizontal-timeline#55]
Would it be possible to format dates displayed on the timeline?
Its default format is MMMM-DD-YYYY, and I would like to use MMMM-YYYY format.

**Comment by ticklepoke** [comment]
searched around and learnt that I can use
`getLabel={function(date) { return date.slice(0, 4); }}`
as props (changing 0,4 accordingly to the index of which characters you need). 
Please let me know if there are any loopholes I overlooked.

**Comment by Nickman87** [comment]
@ticklepoke That is exectly the use of the `getLabel` property, you can use it any way you want to return custom labels.
